### ISSUE TITLE
Getting Symbol(s) not found for architecture x86_64 with latest sdk

### ISSUE THREAD

**Issue by girijeshkumar2007** [Paytm-Payments/Paytm_iOS_App_Kit#2]
after intregating the Paytm bitcode we are continuously getting this error. Please find the screen shot attached.
![screen shot 2016-02-19 at 10 43 48 am](https://cloud.githubusercontent.com/assets/4746279/13167113/babfb2ba-d6f5-11e5-96a8-ee6360337dcd.png)

**Comment by ashfuack** [comment]
Me too facing the same issue some one please help me out

**Comment by lakshayasachdeva1990** [comment]
Experiencing the same

**Comment by girijeshkumar2007** [comment]
any update on this ticket
???

**Comment by vidisha-goel** [comment]
linker error basically comes when the class name or macro or constant name is similar in your project and our libPaymentsSdk.a. .Kindly just rename the concern variable in your project.
