### ISSUE TITLE
Getting checksum changed every time and getting paytm checksum mismatch

### ISSUE THREAD

**Issue by gmpanuku** [Paytm-Payments/Paytm_iOS_App_Kit#27]
I am getting response from my php backend as

```
{
    "CALLBACK_URL" = "https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=REF931544";
    "CHANNEL_ID" = WAP;
    CHECKSUMHASH = "teCofqhADwNJbbdpwujHQpFfNQqR/WiHFTDXqozjioA3nP0ytAYG0XYqvxAHZVpHm4IUV+Qq8Hu8wLM+xXbUOod2kE1gp+tKlFBfihl6VWs=";
    "CUST_ID" = CUS0037;
    EMAIL = "goutham@gmail.com";
    "INDUSTRY_TYPE_ID" = Retail109;
    MID = GOdrin43113348350933;
    "MOBILE_NO" = 9492266928;
    "ORDER_ID" = REF931544;
    "TXN_AMOUNT" = "53.00";
    WEBSITE = GOdrin;
}
```
Same details I am sending to paytm sdk, But I am getting **paytm checksum mismatch** error.
Here is the paytm sdk response
`{\"ORDERID\":\"REF931544\", \"MID\":\"GOdrin43113348350933\", \"TXNAMOUNT\":\"53.00\", \"CURRENCY\":\"INR\", \"STATUS\":\"TXN_FAILURE\", \"RESPCODE\":\"330\", \"RESPMSG\":\"Paytm checksum mismatch.\", \"BANKTXNID\":\"\", \"CHECKSUMHASH\":\"mBFnARynHvgP2DPIYCPeIrZBIhnYFgcrvDev/F+y2ZQ4OQAukS8/fvofNKc964dmwltCvr6IsXDaekdsWABQQaGwhSXSpgQ69KffJbHzxeg=\"}
`
Here is my code
```
let mc = PGMerchantConfiguration.default()!
var orderDict = [String : Any]()
orderDict["MID"] = paramdict["MID"] as! String
orderDict["ORDER_ID"] = paramdict["ORDER_ID"] as! String
orderDict["CUST_ID"] = paramdict["CUST_ID"] as! String
orderDict["INDUSTRY_TYPE_ID"] = paramdict["INDUSTRY_TYPE_ID"] as! String
orderDict["CHANNEL_ID"] = paramdict["CHANNEL_ID"] as! String
orderDict["TXN_AMOUNT"] = paramdict["TXN_AMOUNT"] as! String
orderDict["WEBSITE"] = paramdict["WEBSITE"] as! String
orderDict["CALLBACK_URL"] = paramdict["CALLBACK_URL"] as! String
orderDict["CHECKSUMHASH"] = dict["CHECKSUMHASH"] as! String
orderDict["MOBILE_NO"] = moibile
orderDict["EMAIL"] = email
print(orderDict)
let pgOrder = PGOrder(params: orderDict)
print(pgOrder!)
let transaction = PGTransactionViewController.init(transactionFor: pgOrder)
transaction!.serverType = eServerTypeProduction
transaction!.merchant = mc
transaction!.loggingEnabled = true
transaction!.delegate = self
self.showController(controller: transaction!)

```

So why payment is not successful?, Why i'm getting this error??

**Comment by pradipwalghude** [comment]
Same issue for me? If anyone knows how to resolve it then please text here.

**Comment by pratik2112** [comment]
Same issue for me?

**Comment by amircodiant** [comment]
I was also getting same error.

**Issue** : 
there is an issue in paramsToString function 

function paramsToString(params, mandatoryflag) {
  var data = '';
  var tempKeys = Object.keys(params);
  tempKeys.sort();
  tempKeys.forEach(function (key) {
  var n = params[key].includes("REFUND"); 
   var m = params[key].includes("|");  
        if(n == true )
        {
          params[key] = "";
        }
          if(m == true)
        {
          params[key] = "";
        }  
    if (key !== 'CHECKSUMHASH' ) {
      **if (params[key] === 'null') params[key] = '';**
      if (!mandatoryflag || mandatoryParams.indexOf(key) !== -1) {
        data += (params[key] + '|');
      }
    }
});
  return data;
}

**Note:** for testing payment i was getting BANKNAME = 'NULL'
but this function is checking for lower-case only

**Solutions**
replace that line with given below:
**if (params[key].toLowerCase() === 'null') params[key] = '';**
