### ISSUE TITLE
Optional & Mandatory are inter-changed. (Please fix this for all & please add POD support)

### ISSUE THREAD

**Issue by mahekmshah** [Paytm-Payments/Paytm_iOS_App_Kit#3]
//SSL client certificate settings
@property (nonatomic, copy) NSString    *clientSSLCertPath; //Mandatory: Full path of the client SSL certificate. The certificate has to be placed inside the app bundle
@property (nonatomic, copy) NSString    *clientSSLCertPassword; //Optional: Password for the SSL certificate. Its strongly recommended to set the password for the certificate for additional security

@property (nonatomic, copy) NSString    *checksumGenerationURL; //Optional: If merchant generates checksum in their own server
@property (nonatomic, copy) NSString    *checksumValidationURL; //Optional: If merchant validates checksum in their own server

**Comment by Mohit-Aggarwal1** [comment]
Kindly follow the steps mention in document @ https://paytm-wallet-sdk.readme.io/docs/steps

These comments are for our internal use, Kindly ignore them.
