### ISSUE TITLE
Uploading on App Store error

### ISSUE THREAD

**Issue by BhaktiKarva** [Paytm-Payments/Paytm_iOS_App_Kit#47]
If I select “Do not embed” when linking the library, the app does not run on a physical device. 
If I select “Embed & sign” the app is not validated and I cannot upload on store.
If I select “Embed without signing” the app will not even Install on any physical device.

Please guide on how to solve this issue.

**Comment by tech4solitude** [comment]
@BhaktiKarva  you've to select Embed & sign 
and put the script mentioned in the documentation to get it validated from App Store

**Comment by BhaktiKarva** [comment]
Which script?

**Comment by tech4solitude** [comment]
This one 


if [ "${CONFIGURATION}" = "Release" ]; then
  APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

  # This script loops through the frameworks embedded in the application and
  # removes unused architectures.
  find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
  do
  FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
  FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
  echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

  EXTRACTED_ARCHS=()

  for ARCH in $ARCHS
  do
  echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
  lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
  EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
  done

  echo "Merging extracted architectures: ${ARCHS}"
  lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
  rm "${EXTRACTED_ARCHS[@]}"

  echo "Replacing original executable with thinned version"
  rm "$FRAMEWORK_EXECUTABLE_PATH"
  mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

  done
fi

**Comment by BhaktiKarva** [comment]
It works. Thank you
