### ISSUE TITLE
Domain=NSCocoaErrorDomain Code=3840 "Garbage at end." 

### ISSUE THREAD

**Issue by perlasivakrishna** [Paytm-Payments/Paytm_iOS_App_Kit#5]
I changed my Urls to my server Urls and changed all details like MID etc 

Im getting above error in iOS, Where the Urls are working in android.

**Comment by Mohit-Aggarwal1** [comment]
kindly check

http://stackoverflow.com/questions/25317060/ios-json-error-nsdebugdescription-garbage-at-end
